### ISSUE TITLE
Cucumber Html Report is not available in SauceLabs Automated Test Results WDIO via GitHub Actions

### ISSUE THREAD

**Issue by smtripathi99** [saucelabs/sauce-cucumber-reporter#22]
## Expected Behavior
Cucumber Html Report is  available in SauceLabs Automated Test Results

## Actual Behavior
Cucumber Html Report is not available in SauceLabs Automated Test Results

## Steps to Reproduce the Problem

  1.wdio.config.js
```
 framework: 'cucumber',
    reporters: ['spec',
        ['cucumberjs-json', {
            jsonFolder: './cucumber-reports/cucumber-json',
            language: 'en',
            reportFilePerRetry: true,
            requireModule: ['ts-node/register'],
            format: '@saucelabs/cucumber-reporter'
        }]
    ],
```
<img width="946" alt="SauceRun" src="https://github.com/user-attachments/assets/668d676e-87a6-444f-bb4e-97beceaf3d0b">

  1. Execute via npm test in GitHub Actions
  2. Check the SauceLabs report 
  
[log.json](https://github.com/user-attachments/files/17034075/log.json)

[logs_27.zip](https://github.com/user-attachments/files/17034093/logs_27.zip)

## Specifications

  -node  v18.17.0
  -  "wdio-cucumberjs-json-reporter": "^4.1.4",
  -  "@cucumber/cucumber": "^10.8.0",
    "@wdio/cucumber-framework": "^8.21.0",
    "@wdio/sauce-service": "^8.0.2",
    "@wdio/spec-reporter": "^8.21.0",
    "@saucelabs/cucumber-reporter": "^1.1.1",
    "webdriverio": "^7.16.4",

  - Platform: Window 11 
  - Subsystem:

**Comment by alexplischke** [comment]
This combination is not well supported for a few reasons—nor is it the plugin's original intent.

The plugin would not be aware of the following:
  1. That a WebDriver session is running that's targeting a Sauce Labs browser session. Cucumber is a _test_ framework, so the plugin is unaware of the underlying automation that's being performed, after all, it receive test information from Cucumber and Cucumber is not aware of the automation process either.
  2. That another plugin is creating an artifact (e.g. HTML report) of interest.

**Comment by smtripathi99** [comment]
Thank you @alexplischke for the update so in which scenario this plugin will work any use case or example would be helpful

**Comment by alexplischke** [comment]
It's primary use case is if you are _not_ creating browser sessions with Sauce Labs. For instance, a user might have some pipelines that perform tests on a local grid in addition to Sauce Labs, but would still like to report the results to Sauce Labs, so that all test results are in the same place, achieving some degree of consistency.
